-- Combat skill content. See docs/gameplay/skills/combat.md.
-- Executable F-rank adaptations; higher ranks require verified records.
-- Provenance and deliberate turn-based choices: docs/combat-skills-implementation.md.
local M = {}
M.order = {
	"normal",
	"combat_mastery",
	"defense",
	"smash",
	"counterattack",
	"windmill",
	"assault_slash",
	"critical_hit",
	"dual_wield_mastery",
	"sword_mastery",
	"axe_mastery",
	"shield_mastery",
	"power_shot",
	"double_shot",
}
M.definitions = {
	normal = {
		name = "Attack",
		kind = "attack",
		group = "Combat",
		pool = "sp",
		cost = 2,
		multiplier = 1,
		hits = 1,
		cooldown = 0,
		progression = "combat_mastery",
		target = "hostile",
		tile = "tile_0104",
		description = "Attack with your weapon or unarmed melee. Trains Combat Mastery for every damaging weapon category.",
	},
	combat_mastery = {
		name = "Combat Mastery",
		kind = "passive",
		group = "Combat",
		hero = true,
		target = "self",
		tile = "tile_0104",
		description = "Raises maximum HP and STR. Its attack bonus applies to melee only. Attack costs 2 SP and owner-start recovery is 0.5 SP at F.",
		source = "Combat Mastery F snapshot; project melee midpoint and Attack cost/recovery adaptation.",
		route = "Granted on character creation.",
		ranks = {
			{
				attributes = { hp = 10, str = 1 },
				giant_attributes = { hp = 10, str = 2 },
				melee = { Human = 1.5, Elf = 1, Giant = 1 },
				objectives = {
					{
						id = "damaging_attack",
						event = "normal_damage",
						text = "Deal damage with Attack (any weapon or unarmed)",
						points = 5,
						limit = 20,
					},
				},
			},
		},
	},
	defense = {
		name = "Defend",
		kind = "guard",
		shield_absorption = { small = 0.5, medium = 0.7, large = 1 },
		group = "Combat",
		hero = true,
		pool = "sp",
		cost = 1,
		cooldown = 2,
		target = "self",
		tile = "tile_0090",
		description = "Block one non-magic hit until your next turn starts. Casting and fully blocking incoming hits train separate objectives.",
		source = "Defense F snapshot; project one-hit guard, next owner-start expiry and 2-turn cooldown.",
		route = "Granted on character creation.",
		ranks = {
			{
				attributes = { hp = 2 },
				defense = { Human = 3, Elf = 1, Giant = 5 },
				guard_defense = { Human = 20, Elf = 20, Giant = 30 },
				guard_protection = { Human = 5, Elf = 5, Giant = 10 },
				objectives = {
					{ id = "prepare_guard", event = "guard_use", text = "Commit Defend", points = 5, limit = 20 },
					{
						id = "fully_block",
						event = "guard_block",
						text = "Fully mitigate an incoming attack while guarding",
						points = 5,
						limit = 20,
					},
				},
			},
		},
	},
	smash = {
		name = "Smash",
		kind = "attack",
		group = "Combat",
		hero = true,
		category = "melee",
		pool = "sp",
		cost = 4,
		multiplier = 1.5,
		giant_multiplier = 2,
		hits = 1,
		cooldown = 1,
		bypass_guard = true,
		knockdown = true,
		two_handed_multiplier = 1.2,
		two_handed_critical = 0.05,
		target = "hostile",
		tile = "tile_0104",
		description = "One heavy strike: 1.5× melee (2× for Giants). Bypasses Defense and knocks down. 4 SP.",
		source = "Smash F: 150% Human/Elf, 200% Giant; 4 SP, 1-turn cooldown. No splash or weapon debuffs.",
		route = "Close Combat starter grant, including first rebirth into Close Combat.",
		ranks = {
			{
				attributes = { str = 1, wil = 1 },
				objectives = {
					{
						id = "damaging_skill",
						event = "skill_damage",
						text = "Deal damage with Smash",
						points = 5,
						limit = 20,
					},
				},
			},
		},
	},

	counterattack = {
		name = "Counterattack",
		kind = "counter",
		group = "Combat",
		hero = true,
		category = "melee",
		pool = "sp",
		cost = 2,
		cooldown = 2,
		target = "self",
		tile = "tile_0104",
		description = "Negate one melee hit and retaliate with 50% enemy + 100% own Attack. No critical or chain.",
		source = "Combat spec F adaptation: 2 SP, 2-turn cooldown; expires at next owner start.",
		route = "Learn a free introductory lesson from the skill journal in town.",
		lesson = true,
		ranks = {
			{
				attributes = { dex = 1 },
				enemy_share = 0.5,
				self_share = 1,
				objectives = {
					{
						id = "counter",
						event = "counter_damage",
						text = "Retaliate with Counterattack",
						points = 5,
						limit = 20,
					},
				},
			},
		},
	},
	windmill = {
		name = "Windmill",
		kind = "attack",
		group = "Combat",
		hero = true,
		category = "melee",
		pool = "sp",
		cost = 2,
		cooldown = 1,
		target = "hostile",
		target_rule = "all_living_hostiles",
		multiplier = 1.7,
		hits = 1,
		knockdown = true,
		bypass_counter = true,
		tile = "tile_0104",
		description = "Strike every living enemy for 1.7× melee. Pay 2 SP once. Damaging hits knock down; bypasses Counterattack.",
		source = "Windmill F combat spec: all races 170%; 2 SP, 1-turn cooldown; stable target order.",
		route = "Learn a free introductory lesson from the skill journal in town.",
		lesson = true,
		ranks = {
			{
				attributes = { str = 1, wil = 3 },
				objectives = {
					{
						id = "damaging_skill",
						event = "skill_damage",
						text = "Deal damage with Windmill",
						points = 5,
						limit = 20,
					},
					{
						id = "defeat",
						event = "skill_defeat",
						text = "Defeat distinct enemies with Windmill",
						points = 5,
						limit = 20,
					},
				},
			},
		},
	},
	assault_slash = {
		name = "Assault Slash",
		kind = "attack",
		group = "Combat",
		hero = true,
		category = "melee",
		pool = "sp",
		cost = 5,
		cooldown = 2,
		target = "hostile",
		target_rule = "single_downed_hostile",
		multiplier = 0.7,
		hits = 1,
		bypass_guard = true,
		bypass_counter = true,
		tile = "tile_0104",
		description = "Strike a downed enemy for 0.7× melee. Bypasses Defense and Counterattack. Costs 5 SP.",
		source = "Project combat spec adopts 70%; wiki F is 80% (70% is Novice). Single-target adaptation, no splash.",
		route = "Learn a free introductory lesson from the skill journal in town.",
		lesson = true,
		ranks = {
			{
				attributes = {},
				objectives = {
					{
						id = "damaging_skill",
						event = "skill_damage",
						text = "Damage a downed enemy",
						points = 5,
						limit = 20,
					},
				},
			},
		},
	},
	critical_hit = {
		name = "Critical Hit",
		kind = "passive",
		group = "Combat",
		hero = true,
		target = "self",
		tile = "tile_0104",
		description = "Enables a 10% critical chance and +50% critical damage. One roll per target, shared across hits.",
		source = "F reference +50% critical damage and +3 WIL; 10% chance is authored project content.",
		route = "Learn a free introductory lesson from the skill journal in town.",
		lesson = true,
		ranks = {
			{
				attributes = { wil = 3 },
				critical_chance = 0.1,
				critical_bonus = 0.5,
				objectives = {
					{
						id = "critical",
						event = "critical_damage",
						text = "Deal critical damage",
						points = 5,
						limit = 20,
					},
				},
			},
		},
	},
	dual_wield_mastery = {
		name = "Dual Wield Mastery",
		kind = "passive",
		group = "Combat",
		hero = true,
		target = "self",
		tile = "tile_0104",
		no_elf = true,
		requires_equipment = "paired_swords",
		description = "Adds 2 melee power with two distinct swords. Off-hand weapon power contributes half. Humans and Giants only.",
		source = "F HTML verified via Firecrawl: +2 min/max, 0 STR/Balance/Critical. Count once; no paired guns.",
		route = "Learn a free introductory lesson from the skill journal in town.",
		lesson = true,
		ranks = {
			{
				attributes = {},
				weapon_melee = 2,
				objectives = {
					{
						id = "weapon_damage",
						event = "weapon_damage",
						text = "Deal melee damage with paired swords",
						points = 5,
						limit = 20,
					},
				},
			},
		},
	},
	sword_mastery = {
		name = "Sword Mastery",
		kind = "passive",
		group = "Combat",
		hero = true,
		target = "self",
		tile = "tile_0104",
		requires_equipment = "sword",
		description = "Adds 1.5 melee power with a sword, counted once across both hands.",
		source = "Combat spec F min/max +1/+2 adopted as midpoint +1.5. Balance is reference-only in deterministic damage.",
		route = "Learn a free introductory lesson from the skill journal in town.",
		lesson = true,
		ranks = {
			{
				attributes = {},
				weapon_melee = 1.5,
				objectives = {
					{
						id = "weapon_damage",
						event = "weapon_damage",
						text = "Deal melee damage with a sword",
						points = 5,
						limit = 20,
					},
				},
			},
		},
	},
	axe_mastery = {
		name = "Axe Mastery",
		kind = "passive",
		group = "Combat",
		hero = true,
		target = "self",
		tile = "tile_0104",
		requires_equipment = "axe",
		description = "With an axe: +1.5 melee power and +1 percentage point critical chance when Critical Hit is learned.",
		source = "Combat spec F midpoint +1.5, +1% critical. Armor Pierce stays reference-only.",
		route = "Learn a free introductory lesson from the skill journal in town.",
		lesson = true,
		ranks = {
			{
				attributes = {},
				weapon_melee = 1.5,
				critical_add = 0.01,
				objectives = {
					{
						id = "weapon_damage",
						event = "weapon_damage",
						text = "Deal melee damage with an axe",
						points = 5,
						limit = 20,
					},
				},
			},
		},
	},
	shield_mastery = {
		name = "Shield Mastery",
		kind = "passive",
		group = "Combat",
		hero = true,
		target = "self",
		tile = "tile_0090",
		requires_equipment = "shield",
		description = "With a shield: +0/3/5 Defense for small/medium/large shields and +1% Protection.",
		source = "Combat spec F shield-size rows. Unknown magic bonuses and Auto Defense remain reference-only.",
		route = "Learn a free introductory lesson from the skill journal in town.",
		lesson = true,
		ranks = {
			{
				attributes = {},
				shield = {
					small = { defense = 0, protection = 1 },
					medium = { defense = 3, protection = 1 },
					large = { defense = 5, protection = 1 },
				},
				objectives = {
					{
						id = "shield_block",
						event = "shield_block",
						text = "Fully block a hit with a shield",
						points = 5,
						limit = 20,
					},
				},
			},
		},
	},
	power_shot = {
		name = "Power Shot",
		kind = "attack",
		group = "Combat",
		hero = true,
		category = "ranged",
		no_giant = true,
		pool = "sp",
		cost = 6,
		multiplier = 1.9,
		hits = 1,
		cooldown = 0,
		target = "hostile",
		tile = "tile_0118",
		description = "One deliberate shot for 1.9× ranged attack. Requires a bow; Giants cannot use it.",
		source = "Original Rebirth Dungeon starter action. Not the source game's Ranged Attack.",
		route = "Archery starter grant for Humans and Elves, including rebirth.",
		ranks = {
			{
				attributes = {},
				objectives = {
					{
						id = "damaging_skill",
						event = "skill_damage",
						text = "Deal damage with Power Shot",
						points = 5,
						limit = 20,
					},
				},
			},
		},
	},
	double_shot = {
		name = "Double Shot",
		kind = "attack",
		group = "Combat",
		hero = true,
		category = "guns",
		pool = "sp",
		cost = 6,
		multiplier = 1.8,
		hits = 2,
		cooldown = 0,
		target = "hostile",
		tile = "tile_0124",
		description = "Two hits split 1.8× gun attack. Pay 6 SP once; train once per action. Requires paired guns.",
		source = "Original Rebirth Dungeon starter action; each hit is mitigated separately.",
		route = "Dual Gun starter grant, including first rebirth into Dual Gun.",
		ranks = {
			{
				attributes = {},
				objectives = {
					{
						id = "damaging_skill",
						event = "skill_damage",
						text = "Deal damage with Double Shot",
						points = 5,
						limit = 20,
					},
				},
			},
		},
	},
}
---@param rank integer Zero-based F–1 rank.
---@return number
function M.attack_cost(rank)
	return math.ceil((2 + 0.1 * rank) * 10 - 1e-8) / 10
end

---@param rank integer Zero-based F–1 rank.
---@return number
function M.sp_recovery(rank)
	return 0.5 + 0.5 * math.floor(rank / 3)
end

return M
