import { freeze } from 'immer';
import type { StatusDefinition } from './types';

export const statusDefinitions: Record<string, StatusDefinition> = freeze(
    {
        guard: {
            id: 'guard',
            version: 1,
            name: 'Guard',
            icon: '◈',
            group: 'guard',
            priority: 10,
            duration: 1,
            tags: ['buff'],
            removable: true,
            modifiers: [{ stat: 'defense', flat: 8 }],
        },
        arcaneFocus: {
            id: 'arcaneFocus',
            version: 1,
            name: 'Arcane Focus',
            icon: '✧',
            group: 'arcane-focus',
            priority: 10,
            duration: 3,
            tags: ['buff'],
            removable: true,
            modifiers: [{ stat: 'magicAttack', flat: 6 }],
        },
        strengthDraught: {
            id: 'strengthDraught',
            version: 1,
            name: 'Strength Draught',
            icon: '⚔',
            group: 'strength-draught',
            priority: 10,
            duration: 3,
            tags: ['buff'],
            removable: true,
            modifiers: [{ stat: 'str', flat: 10 }],
        },
        greaterStrength: {
            id: 'greaterStrength',
            version: 1,
            name: 'Greater Strength',
            icon: '⚔',
            group: 'strength-draught',
            priority: 20,
            duration: 3,
            tags: ['buff'],
            removable: true,
            modifiers: [{ stat: 'str', flat: 20 }],
        },
        unstableWeakness: {
            id: 'unstableWeakness',
            version: 1,
            name: 'Unstable Elixir: weakened will',
            icon: '▽',
            group: 'elixir-weakness',
            priority: 10,
            duration: 3,
            tags: ['harmful'],
            removable: true,
            modifiers: [{ stat: 'will', flat: -15 }],
        },
        armorBreak: {
            id: 'armorBreak',
            version: 1,
            name: 'Armor Break',
            icon: '▱',
            group: 'armor-break',
            priority: 10,
            duration: 2,
            tags: ['harmful'],
            removable: true,
            modifiers: [{ stat: 'defense', flat: -4 }],
        },
        exhaustion: {
            id: 'exhaustion',
            version: 1,
            name: 'Exhaustion',
            icon: 'ϟ',
            group: 'exhaustion',
            priority: 10,
            duration: 2,
            tags: ['harmful'],
            removable: true,
            modifiers: [],
            costs: [{ pool: 'stamina', percentBp: 5000 }],
        },
        poison: {
            id: 'poison',
            version: 1,
            name: 'Poison',
            icon: '☠',
            group: 'poison',
            priority: 10,
            duration: 3,
            tags: ['harmful', 'poison'],
            removable: true,
            modifiers: [],
            periodic: [{ kind: 'damage', pool: 'hp', amount: 3, damageType: 'true' }],
        },
        regeneration: {
            id: 'regeneration',
            version: 1,
            name: 'Renewal',
            icon: '♥',
            group: 'regeneration',
            priority: 10,
            duration: 3,
            tags: ['buff'],
            removable: true,
            modifiers: [],
            periodic: [{ kind: 'restore', pool: 'hp', amount: 5 }],
        },
    },
    true,
);