package cloud.vinh.rebirthdungeon

import cloud.vinh.rebirthdungeon.data.content.ContentBundle
import cloud.vinh.rebirthdungeon.data.content.JacksonContentRepository
import cloud.vinh.rebirthdungeon.presentation.screens.LoadingScreen
import com.badlogic.gdx.Gdx
import com.badlogic.gdx.assets.AssetManager
import com.badlogic.gdx.assets.loaders.SkinLoader
import com.badlogic.gdx.graphics.g2d.BitmapFont
import com.badlogic.gdx.graphics.g2d.TextureAtlas
import com.badlogic.gdx.scenes.scene2d.ui.Skin
import ktx.app.KtxGame
import ktx.app.KtxScreen
import ktx.assets.load

/** [KtxGame] shared by all platforms. Owns the application-wide
 * [AssetManager] and the screen coordinator: screens are single-activation
 * instances disposed on navigation, and every managed resource is released
 * only through the manager. Platform launchers construct this class; service
 * interfaces will be injected here as features need them (game-plan section 13).
 *
 * KtxGame's class-keyed screen registry is deliberately unused — navigation
 * hands fresh screen instances to the inherited current-screen slot and keeps
 * the dispose-on-navigate contract through [navigateTo]. */
class RebirthDungeon : KtxGame<KtxScreen>() {
    val presentationSettings = cloud.vinh.rebirthdungeon.presentation.hud.PresentationSettings()
    private var assets: AssetManager? = null
    private var runServices: cloud.vinh.rebirthdungeon.bootstrap.RunServices? = null
    fun runs() = checkNotNull(runServices)
    private var contentBundle: ContentBundle? = null

    fun content(): ContentBundle = checkNotNull(contentBundle) { "Content not validated" }

    fun loadContent() {
        if (contentBundle != null) return
        val bundle = JacksonContentRepository {
            Gdx.files.internal("data/$it").readString("UTF-8")
        }.load()
        bundle.validateVisuals { atlas, frame -> assets().get(atlas, TextureAtlas::class.java).findRegion(frame) != null }
        contentBundle = bundle
        runServices = cloud.vinh.rebirthdungeon.bootstrap.RunServices(bundle.catalog)
    }

    override fun create() {
        assets = AssetManager()
        queueCoreAssets()
        navigateTo(LoadingScreen(this))
    }

    /** The resources every screen relies on. LoadingScreen drains the manager
     * and surfaces failures before any gameplay screen is activated. */
    private fun queueCoreAssets() {
        val manager = assets()
        manager.load<com.badlogic.gdx.audio.Sound>("audio/combat.wav")
        manager.load<TextureAtlas>(DUNGEON_ATLAS)
        manager.load<TextureAtlas>(UI_SKIN_ATLAS)
        // The skin must bind to its atlas at load time, so it needs the
        // explicit SkinParameter overload instead of the typed ktx helper.
        manager.load(UI_SKIN, Skin::class.java, SkinLoader.SkinParameter(UI_SKIN_ATLAS))
        // Title screen fonts (Press Start 2P, generated by tools/MakeTitleFont.java).
        manager.load<BitmapFont>(TITLE_FONT_52)
        manager.load<BitmapFont>(TITLE_FONT_20)
    }

    fun assets(): AssetManager = requireNotNull(assets) { "assets() called before create()" }

    /** Screen transitions go through here: the previous screen is hidden and
     * disposed after the new one takes over, so repeated transitions leak
     * neither GL resources nor input processors. Cached screens arrive with
     * the real menu structure in Phase 7. */
    fun navigateTo(next: KtxScreen) {
        val previous = currentScreen
        previous.hide()
        currentScreen = next
        next.show()
        next.resize(Gdx.graphics.width, Gdx.graphics.height)
        previous.dispose()
    }

    override fun dispose() {
        // KtxGame.dispose only covers its (unused) registry; the current screen
        // is a single-activation instance this coordinator owns.
        currentScreen.hide()
        currentScreen.dispose()
        runServices?.dispose()
        super.dispose()
        assets?.let {
            it.dispose()
            assets = null
        }
    }

    companion object {
        const val DUNGEON_ATLAS = "atlases/dungeon.atlas"
        const val UI_SKIN_ATLAS = "ui/uiskin.atlas"
        const val UI_SKIN = "ui/uiskin.json"
        const val TITLE_FONT_52 = "ui/title-52.fnt"
        const val TITLE_FONT_20 = "ui/title-20.fnt"
    }
}
