extends SceneTree
## Phase 12 one-shot audio synthesizer: writes every game sound as a small
## 16-bit mono WAV under assets/audio/. Run headless to regenerate:
##   godot --headless --path . --script res://tools/generate_audio.gd
## All samples are original, generated by this repository file; no external
## recordings are bundled. Music loops are seamless by construction: every
## voice frequency completes an integer number of cycles across the loop and
## every gain envelope is periodic with the loop length.
const RATE := 22050

func _initialize() -> void:
	_write("ui_click", 0.06, _click())
	_write("dice_roll", 0.30, _dice())
	_write("sword_hit", 0.20, _hit())
	_write("heal", 0.40, _heal())
	_write("door_open", 0.32, _door())
	_write("victory", 0.85, _victory())
	_write("defeat", 1.0, _defeat())
	_write("music_town", 8.0, _pad(8.0, [
		[220.0, 261.625, 329.625],   # A minor
		[174.625, 220.0, 261.625]])  # F major
	)
	_write("music_battle", 6.0, _battle_loop(6.0))
	print("AUDIO_GENERATED: 9 files")
	quit(0)

## --- voice helpers ------------------------------------------------------

func _click() -> Callable:
	return func(t: float) -> float:
		return 0.5 * sin(TAU * 1150.0 * t) * exp(-t * 90.0)

func _dice() -> Callable:
	return func(t: float) -> float:
		var level := 0.0
		for burst: int in 5:
			var start := 0.02 + burst * 0.05
			if t >= start:
				level += exp(-(t - start) * 70.0) * (1.0 - burst * 0.12)
		return level * (_noise(t * 5177.0) * 0.7 + 0.25 * sin(TAU * 240.0 * t))

func _hit() -> Callable:
	return func(t: float) -> float:
		var thump := 0.6 * sin(TAU * 130.0 * t) * exp(-t * 22.0)
		var crack := _noise(t * 6299.0) * exp(-t * 38.0) * 0.7
		return thump + crack

func _heal() -> Callable:
	return func(t: float) -> float:
		var slide := 523.25 + 261.63 * minf(t / 0.30, 1.0)
		return 0.42 * sin(TAU * slide * t) * sin(minf(t, 0.40 - t) * TAU * 2.5)

func _door() -> Callable:
	return func(t: float) -> float:
		var thump := 0.55 * sin(TAU * 82.0 * t) * exp(-t * 16.0)
		var scrape := _noise(t * 3401.0) * exp(-t * 9.0) * 0.35 * sin(minf(t, 0.32 - t) * TAU * 3.1)
		return thump + scrape

func _victory() -> Callable:
	return _sting([523.25, 659.255, 783.99, 1046.5], 0.19, 6.0)

func _defeat() -> Callable:
	return _sting([220.0, 164.814], 0.46, 3.0)

func _sting(notes: Array, step: float, decay: float) -> Callable:
	return func(t: float) -> float:
		var index := mini(int(t / step), notes.size() - 1)
		var local := t - index * step
		var gate: float = minf(local, step - local) * TAU * 6.0
		var body: float = notes[index]
		return 0.42 * (sin(TAU * body * t) + 0.35 * sin(TAU * body * 2.0 * t)) * clampf(gate, 0.0, 1.0) * exp(-local * decay * 0.4)

## Seamless pad: each chord fades in and out on one LFO whose period equals the
## loop; every frequency is quantized to whole cycles across the loop.
func _pad(loop: float, chords: Array) -> Callable:
	var quantized: Array = []
	for chord: Array in chords:
		var voices: Array = []
		for frequency: float in chord:
			voices.append(roundf(frequency * loop) / loop)
		quantized.append(voices)
	return func(t: float) -> float:
		var blend: float = 0.5 + 0.5 * sin(TAU * t / loop)
		var level := 0.0
		for c: int in quantized.size():
			var weight: float = blend if c == 0 else 1.0 - blend
			var chord: Array = quantized[c]
			for v: int in chord.size():
				var voice: float = chord[v]
				level += weight * 0.16 * sin(TAU * voice * t + float(v) * 1.3)
		var breathe: float = 0.85 + 0.15 * sin(TAU * 2.0 * t / loop)
		return level * breathe

func _battle_loop(loop: float) -> Callable:
	var beat: float = loop / 8.0
	var voices: Array = [110.0, roundf(220.0 * loop) / loop, roundf(261.626 * loop) / loop]
	return func(t: float) -> float:
		var beat_index := int(t / beat)
		var local: float = t - beat_index * beat
		var bass := 0.30 * sin(TAU * 55.0 * t) * exp(-local * 7.0)
		var chord := 0.0
		if beat_index % 2 == 0:
			var gate: float = minf(local, beat - local) * TAU / beat
			for v: int in voices.size():
				chord += 0.10 * sin(TAU * voices[v] * t + float(v)) * clampf(gate, 0.0, 1.0)
		var hat: float = _noise(t * 8831.0) * exp(-local * 120.0) * (0.16 if beat_index % 2 == 1 else 0.0)
		return bass + chord + hat

## --- synthesis + wav encoding ------------------------------------------

func _noise(t: float) -> float:
	# Deterministic value noise keeps regeneration byte-stable.
	var cell := floorf(t)
	var fraction: float = t - cell
	var a := _hash(cell)
	var b := _hash(cell + 1.0)
	var smooth: float = fraction * fraction * (3.0 - 2.0 * fraction)
	return (a + (b - a) * smooth) * 2.0 - 1.0

func _hash(cell: float) -> float:
	var value := sin(cell * 12.9898) * 43758.5453
	return value - floorf(value)

func _samples(source: Callable, seconds: float) -> PackedFloat32Array:
	var result := PackedFloat32Array()
	var frames := int(seconds * RATE)
	var peak := 0.0001
	for i: int in frames:
		peak = maxf(peak, absf(source.call(float(i) / RATE)))
	for i: int in frames:
		result.append(clampf(source.call(float(i) / RATE) / peak * 0.86, -1.0, 1.0))
	return result

func _write(name: String, seconds: float, source: Callable) -> void:
	var samples := _samples(source, seconds)
	var data := PackedByteArray()
	data.resize(samples.size() * 2)
	for i: int in samples.size():
		data.encode_s16(i * 2, int(clampf(samples[i], -1.0, 1.0) * 32767.0))
	var stream := PackedByteArray()
	_push(stream, "RIFF".to_ascii_buffer())
	_push_u32(stream, 36 + data.size())
	_push(stream, "WAVEfmt ".to_ascii_buffer())
	_push_u32(stream, 16)
	_push_u16(stream, 1)
	_push_u16(stream, 1)
	_push_u32(stream, RATE)
	_push_u32(stream, RATE * 2)
	_push_u16(stream, 2)
	_push_u16(stream, 16)
	_push(stream, "data".to_ascii_buffer())
	_push_u32(stream, data.size())
	stream.append_array(data)
	var path := "res://assets/audio/%s.wav" % name
	DirAccess.make_dir_recursive_absolute("res://assets/audio")
	var file := FileAccess.open(path, FileAccess.WRITE)
	file.store_buffer(stream)
	file.close()
	print("wrote %s (%d frames)" % [path, samples.size()])

func _push(stream: PackedByteArray, bytes: PackedByteArray) -> void:
	stream.append_array(bytes)

func _push_u32(stream: PackedByteArray, value: int) -> void:
	stream.append(value & 0xFF)
	stream.append((value >> 8) & 0xFF)
	stream.append((value >> 16) & 0xFF)
	stream.append((value >> 24) & 0xFF)

func _push_u16(stream: PackedByteArray, value: int) -> void:
	stream.append(value & 0xFF)
	stream.append((value >> 8) & 0xFF)
