/** Metro requires static references for bundled images; metadata stays in JSON. */
export const atlasAssets: Record<string, number> = {
  dungeon: require('../../assets/game/dungeon.png'),
  'white-spider': require('../../assets/game/enemies/white-spider.png'),
  'black-spider': require('../../assets/game/enemies/black-spider.png'),
  'red-spider': require('../../assets/game/enemies/red-spider.png'),
  'giant-black-spider': require('../../assets/game/enemies/giant-black-spider.png'),
  'oak-tree': require('../../assets/game/decorations/oak-tree.png'),
  'flowering-bush': require('../../assets/game/decorations/flowering-bush.png'),
  'moon-fountain': require('../../assets/game/decorations/moon-fountain.png'),
  'wayfinder-sign': require('../../assets/game/decorations/wayfinder-sign.png'),
  'ember-lantern': require('../../assets/game/decorations/ember-lantern.png'),
  'garden-bench': require('../../assets/game/decorations/garden-bench.png'),
  'cottage-home': require('../../assets/game/decorations/cottage-home.png'),
  'orchard-grocery-home': require('../../assets/game/decorations/orchard-grocery-home.png'),
  'ember-forge-home': require('../../assets/game/decorations/ember-forge-home.png'),
  'herbalist-home': require('../../assets/game/decorations/herbalist-home.png'),
  'wanderer-home': require('../../assets/game/decorations/wanderer-home.png'),
  'npc-keeper': require('../../assets/game/npcs/keeper.png'),
  'npc-grocery-keeper': require('../../assets/game/npcs/grocery-keeper.png'),
  'npc-blacksmith-keeper': require('../../assets/game/npcs/blacksmith-keeper.png'),
  'npc-healer-keeper': require('../../assets/game/npcs/healer-keeper.png'),
  'npc-general-keeper': require('../../assets/game/npcs/general-keeper.png'),
  'warden-supply-chest': require('../../assets/game/decorations/warden-supply-chest.png'),
  'moss-halls-entrance': require('../../assets/game/decorations/moss-halls-entrance.png'),
  'goddess-altar': require('../../assets/game/decorations/goddess-altar.png'),
  'training-manual': require('../../assets/game/decorations/training-manual.png'),
  'sword-manual-binding': require('../../assets/game/decorations/sword-manual-binding.png'),
  'sword-page-grip': require('../../assets/game/decorations/sword-page-grip.png'),
  'sword-page-balance': require('../../assets/game/decorations/sword-page-balance.png'),
  'sword-page-finish': require('../../assets/game/decorations/sword-page-finish.png'),
};
